-- Hand-written data fix: "verifactuMode" existed before VeriFactu records did, as a purely informative
-- choice in the fiscal settings form. Once records started being generated from that same column,
-- companies that had picked a mode there began chaining records (and printing the QR) without ever
-- turning on the switch. Activating through the switch always appends a SYSTEM_START event, so any
-- company with a mode but without that event never confirmed it: its mode goes back to 'pending' and
-- the records generated by mistake (none of them sent to the AEAT) are purged with their chain.
DO $$
DECLARE
  unconfirmed text[];
BEGIN
  SELECT coalesce(array_agg(s."companyId"), '{}') INTO unconfirmed
  FROM "company_settings" s
  WHERE s."verifactuMode" <> 'pending'
    AND NOT EXISTS (
      SELECT 1 FROM "verifactu_event" e WHERE e."companyId" = s."companyId" AND e."eventType" = 'SYSTEM_START'
    );

  IF cardinality(unconfirmed) = 0 THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM "verifactu_record" r
    WHERE r."companyId" = ANY(unconfirmed) AND r."status" NOT IN ('PENDING_SEND', 'NOT_REQUIRED')
  ) THEN
    RAISE EXCEPTION 'VeriFactu: hay registros ya enviados a la AEAT en una empresa sin activación confirmada; revisar a mano';
  END IF;

  -- Explicit purge: the immutability trigger only lets deletes through with this setting.
  PERFORM set_config('verifactu.allow_purge', 'on', true);

  UPDATE "verifactu_chain_head"
  SET "lastRecordId" = NULL, "lastSequence" = 0, "lastHash" = NULL, "updatedAt" = now()
  WHERE "companyId" = ANY(unconfirmed);

  -- Tail first: each record is referenced (ON DELETE RESTRICT) by the next one in the chain.
  WHILE EXISTS (SELECT 1 FROM "verifactu_record" WHERE "companyId" = ANY(unconfirmed)) LOOP
    DELETE FROM "verifactu_record" r
    WHERE r."companyId" = ANY(unconfirmed)
      AND NOT EXISTS (SELECT 1 FROM "verifactu_record" n WHERE n."previousRecordId" = r."id");
  END LOOP;

  UPDATE "company_settings"
  SET "verifactuMode" = 'pending', "verifactuSince" = NULL, "updatedAt" = now()
  WHERE "companyId" = ANY(unconfirmed);
END $$;
