import { describe, expect, it } from "vitest";

import { type ExpenseInvoiceAiAnalysis, toExpenseInvoiceAiDraft } from "@/server/ai/expense-invoice-analysis";

function baseAnalysis(patch: Partial<ExpenseInvoiceAiAnalysis> = {}): ExpenseInvoiceAiAnalysis {
  return {
    supplier_name: "Proveedor Test SL",
    supplier_commercial_name: null,
    supplier_tax_id: "B12345674",
    supplier_vat_number: null,
    supplier_email: null,
    supplier_phone: null,
    supplier_website: null,
    supplier_address: null,
    supplier_postal_code: null,
    supplier_city: null,
    supplier_province: null,
    supplier_country_code: "ES",
    customer_name: null,
    customer_tax_id: null,
    customer_address: null,
    invoice_number: "F-1",
    invoice_series: null,
    invoice_issue_date: "2026-06-03",
    invoice_operation_date: null,
    invoice_due_date: null,
    invoice_received_date: null,
    currency_code: "EUR",
    exchange_rate: 1,
    payment_method: "unknown",
    payment_terms: null,
    supplier_iban: null,
    supplier_bic: null,
    purchase_order_number: null,
    delivery_note_number: null,
    contract_number: null,
    invoice_reference: null,
    description: "Gasto test",
    expense_category: "other",
    suggested_expense_account_code: null,
    is_purchase_order_related: false,
    is_recurring: false,
    recurrence_periodicity: null,
    subtotal_amount: 90,
    discount_amount: 10,
    shipping_amount: 0,
    tax_amount: 18.9,
    retention_amount: 0,
    surcharge_amount: 0,
    rounding_amount: 0,
    total_amount: 108.9,
    paid_amount: 0,
    outstanding_amount: 108.9,
    taxes: [{ tax_type: "VAT", tax_name: "IVA 21%", rate: 21, base_amount: 90, tax_amount: 18.9, deductible_pct: 100 }],
    lines: [],
    validation_totals_match: true,
    validation_taxes_match: true,
    validation_supplier_tax_id_valid: true,
    possible_duplicate: false,
    duplicate_reason: null,
    warnings: [],
    blocking_errors: [],
    confidence_overall: 0.95,
    confidence_supplier: 0.95,
    confidence_supplier_tax_id: 0.95,
    confidence_invoice_number: 0.95,
    confidence_dates: 0.95,
    confidence_amounts: 0.95,
    confidence_lines: 0.95,
    confidence_taxes: 0.95,
    ...patch,
  };
}

describe("expense invoice AI analysis mapping", () => {
  it("uses discounted net base as ERP unit price", () => {
    const draft = toExpenseInvoiceAiDraft(baseAnalysis({
      lines: [{
        line_number: 1,
        description: "Servicio con descuento",
        item_code: null,
        quantity: 1,
        unit_of_measure: null,
        unit_price: 100,
        discount_pct: 10,
        discount_amount: null,
        subtotal_amount: null,
        tax_rate: 21,
        tax_amount: 18.9,
        tax_deductible_pct: 100,
        retention_rate: 0,
        retention_amount: 0,
        total_amount: 108.9,
        suggested_expense_account_code: null,
        cost_center: null,
        project: null,
        department: null,
      }],
    }));

    expect(draft.lines[0]).toMatchObject({
      quantity: 1,
      unitPrice: 90,
      taxRate: 21,
    });
  });
});
